<a href="https://colab.research.google.com/github/kxrrym03/Duolingo-Forgetting-Curve/blob/main/Forgetting_Curve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib

Using matplotlib backend: <object object at 0x78551c71f0c0>

In [3]:
from google.colab import files
uploaded = files.upload()

Saving forgetting_curve.csv to forgetting_curve.csv

In [5]:
df = pd.read_csv('forgetting_curve.csv')
df.shape

(310, 10)

In [6]:
df.head()

,learning_language,language_name,lag_bin,lag_bin_order,practice_bin,practice_bin_order,n_traces,avg_session_recall,item_recall_rate,pct_perfect_sessions
0,all,All languages,<1 hour,0,1-2 exposures,0,383261,0.9157,0.9191,87.37
1,all,All languages,<1 hour,0,3-4 exposures,1,893452,0.9137,0.9177,86.26
2,all,All languages,<1 hour,0,5-9 exposures,2,1429269,0.9129,0.9186,86.50
3,all,All languages,<1 hour,0,10-19 exposures,3,1023779,0.9129,0.9199,86.00
4,all,All languages,<1 hour,0,20+ exposures,4,1239541,0.8995,0.9097,84.58

In [7]:
df.tail()

,learning_language,language_name,lag_bin,lag_bin_order,practice_bin,practice_bin_order,n_traces,avg_session_recall,item_recall_rate,pct_perfect_sessions
305,pt,Portuguese,3+ months,8,1-2 exposures,0,386,0.8765,0.8775,80.05
306,pt,Portuguese,3+ months,8,3-4 exposures,1,812,0.8670,0.8776,77.71
307,pt,Portuguese,3+ months,8,5-9 exposures,2,670,0.8805,0.8791,79.55
308,pt,Portuguese,3+ months,8,10-19 exposures,3,351,0.8649,0.8764,77.21
309,pt,Portuguese,3+ months,8,20+ exposures,4,63,0.8791,0.8923,79.37

In [8]:
df.isnull().sum()

learning_language       0
language_name           0
lag_bin                 0
lag_bin_order           0
practice_bin            0
practice_bin_order      0
n_traces                0
avg_session_recall      0
item_recall_rate        0
pct_perfect_sessions    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

,lag_bin_order,practice_bin_order,n_traces,avg_session_recall,item_recall_rate,pct_perfect_sessions
count,310.000000,310.0000,3.100000e+02,310.000000,310.000000,310.000000
mean,3.935484,2.0000,8.293049e+04,0.888834,0.897956,83.082161
std,2.555981,1.4165,1.573597e+05,0.017793,0.014307,2.836484
min,0.000000,0.0000,6.300000e+01,0.818100,0.851800,72.610000
25%,2.000000,1.0000,1.186825e+04,0.878000,0.888025,81.532500
50%,4.000000,2.0000,3.324150e+04,0.889200,0.898500,83.260000
75%,6.000000,3.0000,8.646775e+04,0.900050,0.905850,84.677500
max,8.000000,4.0000,1.429269e+06,0.932900,0.933700,90.170000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   learning_language     310 non-null    object
 1   language_name         310 non-null    object
 2   lag_bin               310 non-null    object
 3   lag_bin_order         310 non-null    int64
 4   practice_bin          310 non-null    object
 5   practice_bin_order    310 non-null    int64
 6   n_traces              310 non-null    int64
 7   avg_session_recall    310 non-null    float64
 8   item_recall_rate      310 non-null    float64
 9   pct_perfect_sessions  310 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 24.3+ KB

In [12]:
df.dtypes

learning_language        object
language_name            object
lag_bin                  object
lag_bin_order             int64
practice_bin             object
practice_bin_order        int64
n_traces                  int64
avg_session_recall      float64
item_recall_rate        float64
pct_perfect_sessions    float64
dtype: object

In [13]:
df.columns

Index(['learning_language', 'language_name', 'lag_bin', 'lag_bin_order',
       'practice_bin', 'practice_bin_order', 'n_traces', 'avg_session_recall',
       'item_recall_rate', 'pct_perfect_sessions'],
      dtype='object')